### ISSUE TITLE
Refactor approach and design

### ISSUE THREAD

**Issue by slawler** [USACE/wat-go-sdk#38]
@HenryGeorgist @rgoss please take a look at the draft-for-discussion [docs](https://github.com/USACE/wat-go-sdk/tree/feature/docs/docs). There is a workflow and series of structs and methods that *generally* represent the simplified process @HenryGeorgist and I talked through and think describe what is needed for a robust program.

There are a few outstanding questions regarding nomenclature, process, etc. that need to be hashed out, but hopefully the docs here will allow a base from which to hammer out the details and implement the final refactor ahead of testing.

**Comment by HenryGeorgist** [comment]
thanks @slawler I took a quick look. There is alot to process and discuss. Should we convert this to a discussion instead of an issue?

**Comment by HenryGeorgist** [comment]
overcome by events  -new project cloudcompute and cc-go-sdk refactors code
